# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiflip.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QColor
from PyQt5.QtCore import Qt
import rotatescreen
import json
import subprocess
from configparser import ConfigParser


class Ui_MainWindow(object):
    def get_config(self):
        config_get = 'config.ini'
        config_file = ConfigParser()
        config_file.read(config_get)
        final_config = list([(config_file['main']['otduipath']), (config_file['main']['otddaemonpath']), (config_file['main']['otdsettings'])])
        print(final_config)
        return final_config
    def open_and_close_otd(self):
        subprocess.call(["taskkill","/F","/IM","OpenTabletDriver.UX.Wpf.exe"])
        subprocess.call(["taskkill","/F","/IM","OpenTabletDriver.Daemon.exe"])
        SW_MINIMIZE = 6
        info = subprocess.STARTUPINFO()
        info.dwFlags = subprocess.STARTF_USESHOWWINDOW
        info.wShowWindow = SW_MINIMIZE
        SW_HIDE = 0
        info2 = subprocess.STARTUPINFO()
        info2.dwFlags = subprocess.STARTF_USESHOWWINDOW
        info2.wShowWindow = SW_HIDE
        subprocess.Popen(self.get_config()[0], startupinfo=info)
        subprocess.Popen(self.get_config()[1], startupinfo=info2)

    def unflip_button(self):
        screen = rotatescreen.get_primary_display()

        config = open(self.get_config()[2], 'r')
        settings = json.load(config)
        config.close()


        settings["Profiles"][0]["AbsoluteModeSettings"]["Tablet"]["Rotation"] = 0.0
        config = open(self.get_config()[2], 'w')
        json.dump(settings, config)
        config.close()

        self.open_and_close_otd()

        screen.set_landscape()      
        self.label.setText("Your osu! is no longer flipped")
    def flip_button(self):
        screen = rotatescreen.get_primary_display()

        config = open(self.get_config()[2], 'r')
        settings = json.load(config)
        config.close()


        settings["Profiles"][0]["AbsoluteModeSettings"]["Tablet"]["Rotation"] = 180.0
        config = open(self.get_config()[2], 'w')
        json.dump(settings, config)
        config.close()

        self.open_and_close_otd()

        screen.set_landscape_flipped()      
        self.label.setText("Your osu! is no flipped")
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 649)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("osu.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 361, 181))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.flip_button)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 20, 361, 181))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.unflip_button)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 320, 361, 171))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "osu! Flipper"))
        self.pushButton.setText(_translate("MainWindow", "Flip"))
        self.pushButton_2.setText(_translate("MainWindow", "Unflip"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    palette = QPalette()
    palette.setColor(QPalette.Window, QColor(53, 53, 53))
    palette.setColor(QPalette.WindowText, Qt.white)
    palette.setColor(QPalette.Base, QColor(25, 25, 25))
    palette.setColor(QPalette.AlternateBase, QColor(53, 53, 53))
    palette.setColor(QPalette.ToolTipBase, Qt.black)
    palette.setColor(QPalette.ToolTipText, Qt.white)
    palette.setColor(QPalette.Text, Qt.white)
    palette.setColor(QPalette.Button, QColor(53, 53, 53))
    palette.setColor(QPalette.ButtonText, Qt.white)
    palette.setColor(QPalette.BrightText, Qt.red)
    palette.setColor(QPalette.Link, QColor(42, 130, 218))
    palette.setColor(QPalette.Highlight, QColor(42, 130, 218))
    palette.setColor(QPalette.HighlightedText, Qt.black)
    app.setPalette(palette)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
